### ISSUE TITLE
Why can't body be Vec<u8> instead of Vec<Vec<u8>>

### ISSUE THREAD

**Issue by sethdusek** [unbit/uwsgi-rust#4]
I tried using Vec<u8> instead of Vec<Vec<u8>> and it seemed to work fine in my testing, but I may be missing out on something

**Comment by unbit** [comment]
I suppose the "magic" happens here in https://github.com/unbit/uwsgi-rust/blob/master/plugin.rs#L112
the as_ptr() method returns a pointer to an ordered array of char so from the c point of view it is more than enough

**Comment by sethdusek** [comment]
So just doing that with a Vec<u8> should be okay right?
